# Generated by Django 4.2.1 on 2023-05-25 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('namemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.namemodel')),
            ],
            bases=('core.namemodel',),
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('quantity', models.IntegerField()),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('namemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.namemodel')),
            ],
            bases=('core.namemodel',),
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('namemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.namemodel')),
            ],
            bases=('core.namemodel',),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('content', models.TextField()),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Discounts',
            fields=[
                ('namemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.namemodel')),
                ('type', models.CharField(choices=[('CSH', 'cash'), ('PER', 'percent')], max_length=3)),
                ('amount', models.IntegerField()),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('core.namemodel',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('image_address', models.CharField(max_length=255)),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('size', models.CharField(choices=[('xs', 'xsmall'), ('s', 'small'), ('m', 'medium'), ('l', 'large'), ('xl', 'xlarge')], max_length=2)),
                ('quantity', models.IntegerField()),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('total', models.IntegerField()),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('namemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.namemodel')),
                ('price', models.CharField(max_length=255)),
                ('info', models.TextField(max_length=255)),
                ('detail', models.JSONField(blank=True, null=True)),
            ],
            bases=('core.namemodel',),
        ),
        migrations.CreateModel(
            name='ShoppingSession',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basemodel')),
                ('total', models.IntegerField()),
            ],
            bases=('core.basemodel',),
        ),
    ]
